# Generated by Django 4.2.7 on 2023-11-10 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlogmodel',
            options={'verbose_name': 'Login Log'},
        ),
        migrations.AddField(
            model_name='customermodel',
            name='beta_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginlogmodel',
            name='user_agents',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
    ]
