# Generated by Django 4.2.7 on 2023-11-10 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_customer', '0002_alter_loginlogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
