# Generated by Django 4.2.7 on 2023-11-08 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('project', models.IntegerField(blank=True, null=True)),
                ('serp_config', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRootModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=125)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SerpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5)),
                ('country_code', models.IntegerField()),
                ('local_code', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(max_length=15)),
                ('se_domain', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SerpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=45)),
                ('push', models.BooleanField(default=False)),
                ('get', models.BooleanField(default=False)),
                ('main_intent', models.CharField(blank=True, max_length=5, null=True)),
                ('intent_info', models.JSONField(blank=True, max_length=50, null=True)),
                ('check_url', models.CharField(blank=True, max_length=225, null=True)),
                ('item_types', models.CharField(max_length=555)),
                ('se_results_count', models.IntegerField()),
                ('top_10', models.JSONField(blank=True, null=True)),
                ('full_serp_data', models.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_market_explorer.serpconfig')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordrootmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_check_serp', models.BooleanField(default=False)),
                ('root', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('analytics_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordanalysismodel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(max_length=25)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('vol_history', models.JSONField(blank=True, null=True)),
                ('udpate_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordrootmodel')),
            ],
        ),
    ]
