# Generated by Django 4.2.7 on 2023-11-16 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market_explorer', '0005_alter_keywordmodel_root'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordModel',
            new_name='Keyword_KA_Model',
        ),
    ]
