# Generated by Django 4.2.7 on 2023-11-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_explorer', '0006_rename_keywordmodel_keyword_ka_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordKDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KD', models.IntegerField()),
                ('on_update', models.BooleanField(default=False)),
                ('udpate_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_market_explorer.serpconfigmodel')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordrootmodel')),
            ],
            options={
                'verbose_name': 'Keyword Info',
            },
        ),
        migrations.CreateModel(
            name='KeywordVolumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('vol_history', models.JSONField(blank=True, null=True)),
                ('on_update', models.BooleanField(default=False)),
                ('udpate_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_market_explorer.serpconfigmodel')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordrootmodel')),
            ],
            options={
                'verbose_name': 'Keyword Info',
            },
        ),
        migrations.AddField(
            model_name='keywordanalysismodel',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KeywordInfoModel',
        ),
    ]
