# Generated by Django 4.2.7 on 2023-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_explorer', '0010_remove_keyword_ka_model_on_check_serp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_ka_model',
            name='last_update_serp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
