# Generated by Django 4.2.7 on 2023-11-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_explorer', '0012_keywordanalysismodel_keyword_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordanalysismodel',
            name='serp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_market_explorer.serpconfigmodel'),
        ),
    ]
