# Generated by Django 4.2.7 on 2023-11-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market_explorer', '0015_rename_serpmodel_keywordserpmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearchOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=80)),
                ('filter_include', models.TextField(blank=True, null=True)),
                ('filter_exclude', models.TextField(blank=True, null=True)),
                ('filter_volume_min', models.IntegerField(blank=True, null=True)),
                ('filter_volume_max', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='created', max_length=15)),
                ('request_num', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('total_result', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('total_credit', models.IntegerField(default=0)),
                ('cache_total_vol', models.IntegerField(blank=True, null=True)),
                ('cache_total_prev_vol', models.IntegerField(blank=True, null=True)),
                ('cache_vol_history', models.JSONField(blank=True, null=True)),
                ('cache_kd', models.CharField(max_length=25)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_market_explorer.serpconfigmodel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_RS_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('serp', models.IntegerField(blank=True, null=True)),
                ('kd', models.IntegerField(blank=True, null=True)),
                ('volume_history', models.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordrootmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_explorer.keywordresearchordermodel')),
            ],
            options={
                'verbose_name': 'Keyword Info',
            },
        ),
    ]
