# Generated by Django 4.2.7 on 2023-11-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DFAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=125)),
                ('password', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'DF Account',
            },
        ),
    ]
