# Generated by Django 4.2.7 on 2023-11-17 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_connector', '0002_dfrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfrequestlog',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfrequestlog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dfrequestlog',
            name='turnarround_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfrequestlog',
            name='res_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfrequestlog',
            name='res_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfrequestlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfrequestlog',
            name='task_id',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
